import { Header } from '@/components/header/Header';
import { Sidebar } from '@/components/sidebar/Sidebar';
import { AntdProvider } from '@/hooks/antdContext';
import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import { RainbowProvider } from '../../hooks/useRainbowContext';
import '../styles/globals.css';
import '../styles/layout.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Portal',
	description: 'Generated by create next app',
};

export default function LocaleLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	const messages = useMessages();
	// const matches = useMediaQuery('(min-width: 768px)');

	return (
		<html lang={locale}>
			<body className={inter.className} suppressHydrationWarning={true}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<AntdProvider>
						<RainbowProvider>
							<>
								<Header />
								<main>
									<div className='wrapper--sidebar'>
										<Sidebar />
									</div>
									<div className='wrapper--children'>{children}</div>
								</main>
							</>
						</RainbowProvider>
					</AntdProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
